### ISSUE TITLE
Which platform to select when running make generate_manifests 

### ISSUE THREAD

**Issue by jamu85** [slauger/hcloud-okd4#155]
Hi,

I try to create a okd4 cluster on hcloud but I don't know what I have to select when I run 'make generate_manifests'

````
bash-5.1# make generate_manifests
mkdir config
cp install-config.yml config/install-config.yml
openshift-install create manifests --dir=config
? SSH Public Key <none>
? Platform  [Use arrows to move, enter to select, type to filter, ? for more help]
> aws
  azure
  gcp
  libvirt
  openstack
  ovirt
  vsphere
````
Can you help me?

**Comment by slauger** [comment]
Hi,

could you share your `install-config.yaml`? There is no hcloud cloud provider so the install must run with platform `none`.

```
...
platform:
  none: {}
```

Keep in mind that the current versions in the Makefile are a bit outdated. Checkout out https://github.com/openshift/okd/tags for the latest available release.

**Comment by jamu85** [comment]
Sure

````
root@cst-jump-host:~/hcloud-okd4# cat install-config.yml 
---
apiVersion: v1
baseDomain: 'xxx.xx'
metadata:
  name: 'okd4'
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
  machineCIDR:
platform:
  none: {}
pullSecret: '{"auths":{"none":{"auth": "none"}}}'
sshKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIC/O/fb00QeSmKDJ...
````
