### ISSUE TITLE
adjusting replicas does not seem to work

### ISSUE THREAD

**Issue by ebartz** [slauger/hcloud-okd4#75]
Hi Simon,

first of all, this project is really awesome! Thanks for putting all this together.

One thing that does not seem to work for me is having more nodes. I thought that it would be done by specifying a number of workers/masters like this:

``` yaml
---
apiVersion: v1
baseDomain: 'example.com'
metadata:
  name: 'okd4'
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 4
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
  machineCIDR:
platform:
  none: {}
pullSecret: '{"auths":{"none":{"auth": "none"}}}'
sshKey: ssh-rsa AABBCC... Some_Service_User
```

But that did not do the trick for me. Am I missing something?
